version: '3'
services:
  timecat-docs:
    image: registry.cn-hangzhou.aliyuncs.com/oct16/timecat_docs:${IMAGE_TAG}
    build: .
    restart: always
    container_name: timecat-docs
    environment:
      - NODE_ENV=production
    ports:
      - '8700:8700'
