name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'
      - name: Build And Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose build
          docker-compose push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute On Remote Server
        uses: fifsky/ssh-action@master
        with:
          user: '${{ secrets.USER }}'
          host: '${{ secrets.HOST }}'
          key: ${{ secrets.PRIVATE_KEY }}
          command: |
            cd /

            docker login --username=${{ secrets.ACR_USERNAME }} --password=${{ secrets.ACR_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull registry.cn-hangzhou.aliyuncs.com/oct16/timecat_docs:${{ github.sha }}

            docker stop timecat_docs
            docker rm timecat_docs
            docker run -p 5500:5500 --network host -e NODE_ENV=production -d --name timecat_docs registry.cn-hangzhou.aliyuncs.com/oct16/timecat_docs:${{ github.sha }}
